module.exports.inMap = {
  "Smoke": "Smoke",
  "Alcohol": "Alcohol",
  "Car": "Car",
  "Married": "Married",
  "AlreadyHosting": "AlreadyHosting",
  "Phone": "Phone",
  "Allergies": "Allergies",
  "Distance": "Distance",
  "ChildrenName": "ChildrenName",
  "ChildrenGender": "ChildrenGender",
  "ChildrenAge": "ChildrenAge",
  "Hobbies": "Hobbies",
  "Rules": "Rules",
  "PreferredGender": "PreferredGender",
  "PreferredCountry": "PreferredCountry",
  "NoStudentFromCountryStillAssign": "NoStudentFromCountryStillAssign",
  "MarriedOk": "MarriedOk",
  "MarriedWithChildrenOk": "MarriedWithChildrenOk"
};

module.exports.outMap = {
  "Id": "Id",
  "Smoke": "Smoke",
  "Alcohol": "Alcohol",
  "Car": "Car",
  "Married": "Married",
  "AlreadyHosting": "AlreadyHosting",
  "Phone": "Phone",
  "Allergies": "Allergies",
  "Distance": "Distance",
  "ChildrenName": "ChildrenName",
  "ChildrenGender": "ChildrenGender",
  "ChildrenAge": "ChildrenAge",
  "Hobbies": "Hobbies",
  "Rules": "Rules",
  "PreferredGender": "PreferredGender",
  "PreferredCountry": "PreferredCountry",
  "NoStudentFromCountryStillAssign": "NoStudentFromCountryStillAssign",
  "MarriedOk": "MarriedOk",
  "MarriedWithChildrenOk": "MarriedWithChildrenOk",
  "createdAt": "createdAt",
  "updatedAt": "updatedAt"
};
